# Generated by Django 5.2.17 on 2026-08-13 06:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Aguardando pagamento'), ('paid', 'Pago'), ('failed', 'Falhou / cancelado')], default='pending', max_length=10)),
                ('mp_preference_id', models.CharField(blank=True, default='', max_length=120)),
                ('mp_payment_id', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
